security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        user_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: user_provider
            logout:
                target: /
            guard:
                authenticators:
                    - App\Domain\User\Authentication\LoginFormAuthenticator

    access_control:
         - { path: ^/(fr|en)/morvanadmin, roles: ROLE_ADMIN }
