version: 2
jobs:
    checker:
        docker:
            - image: circleci/php:7.2-fpm
        steps:
            - checkout
            - run: sudo php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            - run: sudo php composer-setup.php
            - run: sudo php -r "unlink('composer-setup.php');"
            - run: sudo php -d memory_limit=-1 composer.phar install -n --optimize-autoloader --apcu-autoloader
            - run: sudo php -d memory_limit=-1 composer.phar dump-autoload --optimize --apcu
            - run: ./bin/console d:d:c --env=test
            - run: ./bin/console d:s:u --env=test --force
            - run:
                  name: Install PHP libzip-dev
                  command: sudo apt-get install -y libzip-dev
            - run:
                  name: Install PHP zip
                  command: sudo docker-php-ext-install zip
            - run:
                  name: Check Coding Style
                  command: vendor/bin/phpcs
            - run:
                  name: Check Deptrac
                  command: vendor/bin/deptrac
            - run:
                  name: Check PHPStan
                  command: vendor/bin/phpstan analyze src
            - run:
                  name: Valid functional tests
                  command: vendor/bin/behat
            -   run:
                  name: Valid unit tests
                  command: vendor/bin/simple-phpunit

workflows:
    version: 2
    checker:
        jobs:
            - checker
