root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: '/fr'
        permanent: true

easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
    prefix: /{_locale}/morvanadmin
    requirements:
        _locale: en|fr

    type: annotation
